### PR TITLE
Added a toggle for the image path check at the end of hook.ts

### PR DESCRIPTION
**Pull request by FabulousCodingFox**

### CODE REVIEW

**Comment by FabulousCodingFox** [comment]
Readme need to be updated

**Comment by FabulousCodingFox** [comment]
See #27

**Comment by dan-cooke** [comment]
Any reason why you closed this @FabulousCodingFox  

I agree that this should be optional. This plugin just simply doesn't work for monorepos, where the output path is not the path assumed by the author

**Comment by FabulousCodingFox** [comment]
> Any reason why you closed this @FabulousCodingFox
> 
> I agree that this should be optional. This plugin just simply doesn't work for monorepos, where the output path is not the path assumed by the author

This was pull was not needed after working Windows support

**Pull request closed without merging**
